require('./jsonToXml-test')
require('./mergeOutlookConditionnals-test')
require('./minifyOutlookConditionnals-test')
require('./shorthandParser-test')
require('./skeleton-test')
require('./widthParser-test')
