export default {
  'mj-accordion': [ 'mj-accordion-element' ],
  'mj-accordion-element': [
    'mj-accordion-title',
    'mj-accordion-text',
  ],
  'mj-accordion-title': [],
  'mj-accordion-text': [],
  'mj-body': [
    'mj-container',
    'mj-raw',
  ],
  'mj-button': [],
  'mj-carousel': [ 'mj-carousel-image' ],
  'mj-carousel-image': [],
  'mj-column':[
    'mj-accordion',
    'mj-button',
    'mj-carousel',
    'mj-divider',
    'mj-html',
    'mj-image',
    'mj-inline-links',
    'mj-invoice',
    'mj-list',
    'mj-location',
    'mj-raw',
    'mj-social',
    'mj-spacer',
    'mj-table',
    'mj-text',
  ],
  'mj-container': [
    'mj-hero',
    'mj-navbar',
    'mj-raw',
    'mj-section',
    'mj-wrapper',
  ],
  'mj-divider': [],
  'mj-group': [
    'mj-column',
    'mj-raw',
  ],
  'mj-hero': [ 'mj-hero-content' ],
  'mj-hero-content': [
    'mj-accordion',
    'mj-button',
    'mj-carousel',
    'mj-divider',
    'mj-html',
    'mj-image',
    'mj-list',
    'mj-location',
    'mj-social',
    'mj-spacer',
    'mj-table',
    'mj-text',
  ],
  'mj-html': [],
  'mj-image': [],
  'mj-inline-links': [ 'mj-link' ],
  'mj-invoice': [ 'mj-invoice-item' ],
  'mj-invoice-item': [],
  'mj-link': [],
  'mj-list': [],
  'mj-location': [],
  'mj-navbar': [
    'mj-column',
    'mj-group',
    'mj-raw',
  ],
  'mj-raw': [],
  'mj-section': [
    'mj-column',
    'mj-group',
    'mj-raw',
  ],
  'mj-social': [],
  'mj-spacer': [],
  'mj-table': [],
  'mj-text': [],
  'mj-wrapper': [
    'mj-hero',
    'mj-navbar',
    'mj-raw',
    'mj-section'
  ],
}
