require('./html-attributes.test')
require('./lazy-head-style.test')
require('./tableWidth.test')
require('./wrapper-border-radius.test')
require('./accordionTitle-fontWeight.test')
require('./fontUrls-multiples.test')
