export validAttributes from './validAttributes'
export validChildren from './validChildren'
export validTag from './validTag'
export validTypes from './validTypes'
export errorAttr from './errorAttr'
