name: Build Standalone Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 4.15.3)'
        required: true
        default: '4.15.3'

jobs:
  build-executables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build executable for ${{ matrix.os }}
        run: |
          cd packages/mjml-cli
          yarn build
          pkg . --targets node18-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'macos' }}-x64 --output mjml-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'macos' }}-x64
        shell: bash

      - name: Upload executable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mjml-executable-${{ matrix.os }}
          path: packages/mjml-cli/mjml-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'macos' }}-x64*
          retention-days: 30

  create-release:
    needs: build-executables
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/mjml-executable-ubuntu-latest/mjml-linux-x64
            ./artifacts/mjml-executable-windows-latest/mjml-win-x64.exe
            ./artifacts/mjml-executable-macos-latest/mjml-macos-x64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 